version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
    container_name: dnmp-nginx
    networks:
      docker_net:
        ipv4_address: ${NGINX_IP}

  php72:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP72_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHP_EXTENSIONS: ${PHP72_EXTENSIONS}
        MORE_EXTENSION_INSTALLER: php72.sh
    ports:
      - "${XDEBUG72_HOST_PORT}:${XDEBUG72_HOST_PORT}"
      - "${SWOOLE72_HOST_PORT}:${SWOOLE72_HOST_PORT}"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP72_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP72_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP72_LOG_DIR}:/var/log/php
    restart: always
    container_name: dnmp-php72
    cap_add:
      - SYS_PTRACE
    networks:
      docker_net:
        ipv4_address: ${PHP72_IP}

  php56:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP56_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHP_EXTENSIONS: ${PHP56_EXTENSIONS}
        MORE_EXTENSION_INSTALLER: php56.sh
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP56_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP56_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP56_LOG_DIR}:/var/log/php
    cap_add:
      - SYS_PTRACE
    container_name: dnmp-php56
    networks:
      docker_net:
        ipv4_address: ${PHP56_IP}

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    container_name: dnmp-mysql
    networks:
      docker_net:
        ipv4_address: ${MYSQL_IP}
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    container_name: dnmp-redis
    networks:
      docker_net:
        ipv4_address: ${REDIS_IP}
    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "${PHPMYADMIN_HOST_PORT}:80"
    networks:
      docker_net:
        ipv4_address: ${MYSQL_ADMIN_IP}
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    ports:
      - "${REDISMYADMIN_HOST_PORT}:80"
    networks:
      docker_net:
        ipv4_address: ${REDIS_ADMIN_IP}
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379

  portainer:
    image: portainer/portainer:latest
    ports:
      - "${PORTAINER_HOST_PORT}:9000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:cached
      - ./portainer/:/data:cached
    networks:
      docker_net:
        ipv4_address: ${PORTAINER_IP}

networks:
  docker_net:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: "${DOCKER_SUBNET}"
